import feedparser

def get_all_posts(rss_url):
    feed = feedparser.parse(rss_url)
    posts = []
    for entry in feed.entries:
        posts.append({
            "title": entry.title,
            "content": entry.summary, 
            "description": f"Original Post: {entry.link}\n\nGenerated by AI Automation."
        })
    return posts
