"""
Prompt templates package.
"""

from .templates import (
    SYSTEM_PROMPT_ASSISTANT,
    SYSTEM_PROMPT_RESEARCHER,
    SYSTEM_PROMPT_CODER,
    TASK_SUMMARIZATION,
    TASK_ANALYSIS,
    TASK_CODE_REVIEW,
    AGENT_COORDINATOR,
    TOOL_USE_PROMPT
)

__all__ = [
    'SYSTEM_PROMPT_ASSISTANT',
    'SYSTEM_PROMPT_RESEARCHER',
    'SYSTEM_PROMPT_CODER',
    'TASK_SUMMARIZATION',
    'TASK_ANALYSIS',
    'TASK_CODE_REVIEW',
    'AGENT_COORDINATOR',
    'TOOL_USE_PROMPT'
]
