'use client';

import { useState, useEffect } from 'react';
import { useApp } from '@/context/AppContext';
import {
  CloudArrowDownIcon,
  CloudArrowUpIcon,
  CloudIcon,
  DocumentTextIcon,
  CheckCircleIcon,
  PlayIcon,
  ArrowPathIcon,
  FolderIcon,
  CodeBracketIcon,
  ServerIcon,
  CircleStackIcon,
  CpuChipIcon,
  PlusIcon,
  XMarkIcon,
  DocumentArrowDownIcon,
} from '@heroicons/react/24/outline';
import { LineChart, BarChart } from '@/components/Charts';

export default function GcpTerraformMigratePage() {
  const { theme } = useApp();

  // Product state
  const [productEnabled, setProductEnabled] = useState(true);

  // GCP connection state
  const [gcpConnected, setGcpConnected] = useState(false);
  const [projectId, setProjectId] = useState('');
  const [regions, setRegions] = useState(['us-central1']);

  // Migration state
  const [migrationInProgress, setMigrationInProgress] = useState(false);
  const [migrationProgress, setMigrationProgress] = useState(0);
  const [discoveredResources, setDiscoveredResources] = useState(null);
  const [terraformCode, setTerraformCode] = useState(null);
  const [selectedResources, setSelectedResources] = useState([]);

  // Add/Remove region inputs
  const addRegion = () => {
    setRegions([...regions, '']);
  };

  const removeRegion = (index) => {
    if (regions.length > 1) {
      setRegions(regions.filter((_, i) => i !== index));
    }
  };

  const updateRegion = (index, value) => {
    const newRegions = [...regions];
    newRegions[index] = value;
    setRegions(newRegions);
  };

  const handleGcpConnect = () => {
    // Mock connection
    setGcpConnected(true);
  };

  const handleDiscoverResources = () => {
    setMigrationInProgress(true);
    setMigrationProgress(0);

    const interval = setInterval(() => {
      setMigrationProgress((prev) => {
        if (prev >= 100) {
          clearInterval(interval);
          setMigrationInProgress(false);
          setDiscoveredResources([
            { id: 'vm-1', name: 'gke-cluster-prod', type: 'GKE Cluster', region: 'us-central1' },
            { id: 'vm-2', name: 'cloud-sql-db', type: 'Cloud SQL Instance', region: 'us-central1' },
            { id: 'vm-3', name: 'compute-instance-1', type: 'Compute Engine', region: 'us-central1' },
            { id: 'st-1', name: 'static-assets-bucket', type: 'Cloud Storage', region: 'us-central1' },
            { id: 'net-1', name: 'vpc-main', type: 'VPC Network', region: 'global' },
          ]);
          return 100;
        }
        return prev + 10;
      });
    }, 500);
  };

  const handleGenerateTerraform = () => {
    setTerraformCode(`
# Generated by AI-a NextGen GCP Migration
# Timestamp: ${new Date().toISOString()}

provider "google" {
  project = "${projectId}"
  region  = "us-central1"
}

resource "google_container_cluster" "primary" {
  name     = "gke-cluster-prod"
  location = "us-central1"
  
  remove_default_node_pool = true
  initial_node_count       = 1
}

resource "google_sql_database_instance" "main" {
  name             = "cloud-sql-db"
  database_version = "POSTGRES_14"
  region           = "us-central1"

  settings {
    tier = "db-f1-micro"
  }
}

resource "google_storage_bucket" "static" {
  name          = "static-assets-bucket-${projectId}"
  location      = "US"
  force_destroy = true
}

resource "google_compute_network" "vpc_network" {
  name = "vpc-main"
}
`);
  };

  return (
    <div className="space-y-6">
      {/* Header */}
      <div className="flex items-center justify-between">
        <div>
          <h1 className="text-3xl font-bold text-gray-900 dark:text-white mb-2">
            GCP to Terraform Migrate
          </h1>
          <p className="text-gray-600 dark:text-gray-400">
             Automated Infrastructure as Code (IaC) generation from Google Cloud Platform resources.
          </p>
        </div>
        <div className="flex items-center gap-4">
          <span className={`px-4 py-2 rounded-full text-sm font-medium ${
            productEnabled ? 'bg-green-100 text-green-700' : 'bg-red-100 text-red-700'
          }`}>
            {productEnabled ? 'Active' : 'Disabled'}
          </span>
        </div>
      </div>

       {/* Connection Status */}
       <div className="bg-white dark:bg-gray-800 rounded-lg border border-gray-200 dark:border-gray-700 p-6">
        <div className="flex items-center gap-3 mb-6">
          <CloudIcon className="h-8 w-8 text-primary" aria-hidden="true" />
          <h2 className="text-2xl font-bold text-gray-900 dark:text-white">
            GCP Connection Settings
          </h2>
        </div>

        {!gcpConnected ? (
          <div className="space-y-4">
            <div>
              <label className="block text-sm font-medium text-gray-700 dark:text-gray-300 mb-2">
                GCP Project ID *
              </label>
              <input
                type="text"
                value={projectId}
                onChange={(e) => setProjectId(e.target.value)}
                placeholder="my-gcp-project-id"
                className="w-full px-4 py-2 border border-gray-300 dark:border-gray-600 rounded-lg focus:ring-2 focus:ring-primary dark:bg-gray-700 dark:text-white"
                disabled={!productEnabled}
              />
            </div>

            <div>
              <div className="flex items-center justify-between mb-2">
                <label className="block text-sm font-medium text-gray-700 dark:text-gray-300">
                  Target Regions *
                </label>
                <button
                  onClick={addRegion}
                  disabled={!productEnabled}
                  className="flex items-center gap-2 px-3 py-1 text-sm bg-primary/10 text-primary rounded-lg hover:bg-primary/20 transition-colors disabled:opacity-50"
                >
                  <PlusIcon className="h-4 w-4" />
                  Add Region
                </button>
              </div>
              <div className="space-y-3">
                {regions.map((rg, index) => (
                  <div key={index} className="flex items-center gap-2">
                    <input
                      type="text"
                      value={rg}
                      onChange={(e) => updateRegion(index, e.target.value)}
                      placeholder={`us-central1`}
                      className="flex-1 px-4 py-2 border border-gray-300 dark:border-gray-600 rounded-lg focus:ring-2 focus:ring-primary dark:bg-gray-700 dark:text-white"
                      disabled={!productEnabled}
                    />
                    {regions.length > 1 && (
                      <button
                        onClick={() => removeRegion(index)}
                        disabled={!productEnabled}
                        className="p-2 text-red-600 hover:bg-red-50 dark:hover:bg-red-900/20 rounded-lg transition-colors disabled:opacity-50"
                        aria-label="Remove region"
                      >
                        <XMarkIcon className="h-5 w-5" />
                      </button>
                    )}
                  </div>
                ))}
              </div>
            </div>

            <button
              onClick={handleGcpConnect}
              disabled={!productEnabled || !projectId || regions.filter(rg => rg.trim()).length === 0}
              className="px-6 py-2 bg-primary hover:opacity-90 text-white rounded-lg font-medium disabled:opacity-50 disabled:cursor-not-allowed transition-colors"
            >
              Connect to GCP
            </button>
            <p className="text-sm text-gray-500 dark:text-gray-400">
              {/* TODO: Backend - Use Google Cloud SDK for authentication */}
              Secure connection using Google Cloud IAM authentication with Viewer permissions.
            </p>
          </div>
        ) : (
          <div className="flex items-center gap-4">
            <CheckCircleIcon className="h-8 w-8 text-green-500" />
            <div className="flex-1">
              <p className="text-gray-900 dark:text-white font-medium">
                Connected to GCP Project
              </p>
              <p className="text-sm text-gray-500 dark:text-gray-400">
                {projectId} | {regions.filter(rg => rg.trim()).length} region(s)
              </p>
            </div>
            <button
              onClick={() => setGcpConnected(false)}
              className="px-4 py-2 text-red-600 hover:text-red-700 dark:text-red-400 dark:hover:text-red-300 font-medium"
            >
              Disconnect
            </button>
          </div>
        )}
      </div>

       {/* Migration Workflow */}
       <div className="bg-white dark:bg-gray-800 rounded-lg border border-gray-200 dark:border-gray-700 p-6">
        <h3 className="text-lg font-semibold text-gray-900 dark:text-white mb-6">
          Migration Workflow
        </h3>

        <div className="grid grid-cols-1 md:grid-cols-4 gap-4">
          {/* Step 1 */}
          <div className={`p-5 rounded-lg border-2 ${
            gcpConnected ? 'border-green-500 bg-green-50 dark:bg-green-900/20' : 'border-gray-300 dark:border-gray-600'
          }`}>
            <div className="flex justify-center mb-3">
              <CloudArrowUpIcon className={`h-10 w-10 ${gcpConnected ? 'text-green-600' : 'text-gray-400'}`} />
            </div>
            <p className="text-center font-semibold text-gray-900 dark:text-white mb-1">1. Connect</p>
            <p className="text-xs text-center text-gray-600 dark:text-gray-400">GCP Project</p>
          </div>

          {/* Step 2 */}
          <div className={`p-5 rounded-lg border-2 ${
            discoveredResources ? 'border-green-500 bg-green-50 dark:bg-green-900/20' : 'border-gray-300 dark:border-gray-600'
          }`}>
            <div className="flex justify-center mb-3">
              <ServerIcon className={`h-10 w-10 ${discoveredResources ? 'text-green-600' : 'text-gray-400'}`} />
            </div>
            <p className="text-center font-semibold text-gray-900 dark:text-white mb-1">2. Discover</p>
            <p className="text-xs text-center text-gray-600 dark:text-gray-400">GCP Resources</p>
          </div>

          {/* Step 3 */}
          <div className={`p-5 rounded-lg border-2 ${
            terraformCode ? 'border-green-500 bg-green-50 dark:bg-green-900/20' : 'border-gray-300 dark:border-gray-600'
          }`}>
            <div className="flex justify-center mb-3">
              <CodeBracketIcon className={`h-10 w-10 ${terraformCode ? 'text-green-600' : 'text-gray-400'}`} />
            </div>
            <p className="text-center font-semibold text-gray-900 dark:text-white mb-1">3. Generate</p>
            <p className="text-xs text-center text-gray-600 dark:text-gray-400">Terraform Code</p>
          </div>

          {/* Step 4 */}
          <div className={`p-5 rounded-lg border-2 ${
            terraformCode ? 'border-primary bg-primary/10' : 'border-gray-300 dark:border-gray-600'
          }`}>
            <div className="flex justify-center mb-3">
              <DocumentArrowDownIcon className={`h-10 w-10 ${terraformCode ? 'text-primary' : 'text-gray-400'}`} />
            </div>
            <p className="text-center font-semibold text-gray-900 dark:text-white mb-1">4. Download</p>
            <p className="text-xs text-center text-gray-600 dark:text-gray-400">Terraform Files</p>
          </div>
        </div>

        {/* Action Buttons */}
        <div className="flex items-center gap-4 mt-6">
          {!discoveredResources ? (
            <button
              onClick={handleDiscoverResources}
              disabled={!productEnabled || !gcpConnected || migrationInProgress}
              className="px-6 py-3 bg-gradient-to-r from-primary to-primary/80 hover:opacity-90 text-white rounded-lg font-semibold flex items-center gap-2 disabled:opacity-50 disabled:cursor-not-allowed transition-all shadow-lg"
            >
              {migrationInProgress ? (
                <>
                  <ArrowPathIcon className="h-5 w-5 animate-spin" />
                  Discovering Resources ({migrationProgress}%)...
                </>
              ) : (
                <>
                  <PlayIcon className="h-5 w-5" />
                  Start Discovery
                </>
              )}
            </button>
          ) : (
             <div className="flex gap-4">
                 <button
                   onClick={() => {
                     setDiscoveredResources(null);
                     setTerraformCode(null);
                   }}
                   className="px-6 py-3 bg-white border border-gray-300 dark:bg-gray-700 dark:border-gray-600 text-gray-700 dark:text-white rounded-lg font-semibold hover:bg-gray-50 dark:hover:bg-gray-600 transition-colors"
                 >
                   Reset
                 </button>
                 {!terraformCode && (
                  <button
                    onClick={handleGenerateTerraform}
                     className="px-6 py-3 bg-gradient-to-r from-green-600 to-teal-600 hover:from-green-700 hover:to-teal-700 text-white rounded-lg font-semibold flex items-center gap-2 transition-all shadow-lg"
                  >
                     <CodeBracketIcon className="h-5 w-5" />
                     Generate Terraform
                  </button>
                 )}
             </div>
          )}
        </div>
      </div>

      {discoveredResources && (
        <div className="grid grid-cols-1 lg:grid-cols-2 gap-6 animate-fade-in-up">
           {/* Resource List */}
           <div className="bg-white dark:bg-gray-800 rounded-lg border border-gray-200 dark:border-gray-700 p-6">
              <h3 className="text-lg font-semibold text-gray-900 dark:text-white mb-4 flex items-center gap-2">
                 <ServerIcon className="h-5 w-5 text-primary" />
                 Discovered Resources
              </h3>
              <div className="max-h-96 overflow-y-auto space-y-2">
                  {discoveredResources.map((res) => (
                     <div key={res.id} className="flex items-center justify-between p-3 bg-gray-50 dark:bg-gray-700/50 rounded-lg border border-gray-100 dark:border-gray-700">
                        <div>
                           <p className="font-medium text-gray-900 dark:text-white text-sm">{res.name}</p>
                           <p className="text-xs text-gray-500">{res.type} • {res.region}</p>
                        </div>
                        <CheckCircleIcon className="h-5 w-5 text-green-500" />
                     </div>
                  ))}
              </div>
           </div>

           {/* Terraform Code Preview */}
           {terraformCode && (
             <div className="bg-gray-900 rounded-lg border border-gray-700 p-6 flex flex-col h-full">
                <div className="flex items-center justify-between mb-4">
                   <h3 className="text-lg font-semibold text-white flex items-center gap-2">
                      <CodeBracketIcon className="h-5 w-5 text-green-400" />
                      main.tf Preview
                   </h3>
                    <button className="text-sm text-green-400 hover:text-green-300">
                       Copy Code
                    </button>
                </div>
                <pre className="flex-1 overflow-auto text-sm font-mono text-gray-300 bg-black/50 p-4 rounded-lg">
                   {terraformCode}
                </pre>
                <div className="mt-4 pt-4 border-t border-gray-800">
                    <button className="w-full py-2 bg-primary hover:opacity-90 text-white rounded-lg font-medium transition-colors">
                       Download Project Files (.zip)
                    </button>
                </div>
             </div>
           )}
        </div>
      )}
    </div>
  );
}
